version: '3.8'

services:
  express-app:
    build: .
    container_name: express-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/webhookDB
      - JWT_SECRET=your_jwt_secret
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka
    command: npm start
    env_file:
      - .env

  ui:
    build:
      context: ./spenza_ui
    ports:
      - "8080:80"     # React served on localhost:8080
    depends_on:
      - express-app

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

volumes:
  mongo-data:
